name: Full Flutter CI

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      upload-artifact:
        type: boolean
        description: 'Upload build artifacts to Release'
        default: true
      upload-tag:
        type: string
        description: 'Release Tag'
        default: 'nightly'
  pull_request:
    paths-ignore:
    - "docs/**"
    - "README.md"
  push:
    branches:
      - master
    paths-ignore:
      - "docs/**"
      - "README.md"

jobs:
  run-ci:
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: ${{ inputs.upload-artifact == true }}
      upload-tag: ${{ inputs.upload-tag || 'nightly' }}
